# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# coverMean60.py
# Created on: 2018-05-22 17:52:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Dryas_ajanensis_cover = "K:\\VegetationEcology\\NorthSlopeDataHarmonization\\Project_GIS\\DataHarmonization_GIS.gdb\\Dryas_ajanensis_cover"
Dryas_ajanensis_cover__3_ = "K:\\VegetationEcology\\NorthSlopeDataHarmonization\\Project_GIS\\DataHarmonization_GIS.gdb\\Dryas_ajanensis_cover"

# Process: Point to Raster
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "K:\\VegetationEcology\\NorthSlopeDataHarmonization\\Project_GIS\\DataHarmonization_GIS.gdb\\StudyArea_Raster"
arcpy.PointToRaster_conversion(Dryas_ajanensis_cover, "cover", Dryas_ajanensis_cover__3_, "MEAN", "NONE", "60")
arcpy.env.snapRaster = tempEnvironment0

